"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os, datetime

load_dotenv()
VA_API_URL = os.getenv('VA_API_URL')
VA_CLIENT_ID = '0oax7g1h68fkSGhHT2p7'
JWT_CLIENT_ID = '0oaxj51zcfaczzOaw2p7'
VA_REDIRECT_URI = 'http://localhost:8000/api/oauth/callback/'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k^&20u1%#qe_p&8keuqpb7hg5_nmj!qadai4@nvxz1@#h=s^7w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_REDIRECT_URI_SCHEMES = ['http', 'https', 'yourapp']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'appSettings',
    'oauth2_provider',
    'rest_framework.authtoken',
    'chatbot',
    # 'documents',    # tony
    # 'ai_dex',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'api.middleware.AllowCustomSchemeMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': 'myprojectdb',
        # 'USER': 'myprojectuser',
        # 'PASSWORD': 'mypassword',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Tony
# Media files
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Google Cloud credentials
# GOOGLE_APPLICATION_CREDENTIALS = os.path.join(BASE_DIR, '../vugle-health-431600-c998419c9312.json')
# GCLOUD_PROJECT = 'vugle-health-431600'
# DOCUMENT_AI_PROCESSOR_ID = 'd544f32e83e0e56'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # "rest_framework.permissions.IsAuthenticated",
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',    
        
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# JWT_AUTH = {
#     # how long the original token is valid for
#     'JWT_EXPIRATION_DELTA': datetime.timedelta(days=3),
#     # allow refreshing of tokens
#     'JWT_ALLOW_REFRESH': True,
# }

CORS_ALLOW_ORIGINS = [
     'http://localhost:8000',
     'exp://192.168.50.115:8081',
]
CORS_ALLOWS_CREDENTIALS = True


OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    'OAUTH2_VALIDATOR_CLASS': 'oauth2_provider.oauth2_validators.OAuth2Validator',
    'SCOPES': {
        'profile': 'Read user profile information',
        'openid': 'OpenID Connect',
        'offline_access': 'Offline access',
        'disability_rating.read': 'Read disability rating',
        'service_history.read': 'Read service history',
        'veteran_status.read': 'Read veteran status',
    }
}

SESSION_OP_AUTHORIZATION_URL = 'oidc_op_authorization_url'
SESSION_OP_TOKEN_URL = 'oidc_op_token_url'
SESSION_OP_USERINFO_URL = 'oidc_op_userinfo_url'
SESSION_OP_JWKS_URL = 'oidc_op_jwks_url'
SESSION_OP_JWKS = 'oidc_op_jwks'
SESSION_OP_END_SESSION_URL = 'oidc_op_end_session_url'
SESSION_OP_CLAIMS_PARAMETER_SUPPORTED = 'oidc_op_claims_parameter_supported'
SESSION_NEXT_URL = 'oidc_next_url'
SESSION_FAIL_URL = 'oidc_fail_url'
SESSION_STATE = 'oidc_state'
SESSION_NONCE = 'oidc_nonce'
SESSION_CHALLENGE = 'oidc_challenge'
SESSION_ID_TOKEN = 'oidc_id_token'
SESSION_ACCESS_TOKEN = 'oidc_access_token'
SESSION_ACCESS_EXPIRES_AT = 'oidc_access_expires_at'
SESSION_REFRESH_TOKEN = 'oidc_refresh_token'
SESSION_EXPIRES_AT = 'oidc_expires_at'
SESSION_LOGOUT_STATE = 'oidc_logout_state'
OIDC_URL_AUTHENTICATION_NAME = 'oidc_authentication'
OIDC_URL_CALLBACK_NAME = 'oidc_callback'
OIDC_URL_LOGOUT_NAME = 'oidc_logout'
OIDC_URL_TOTAL_LOGOUT_NAME = 'oidc_total_logout'
OIDC_URL_LOGOUT_BY_OP_NAME = 'oidc_logout_by_op'
OIDC_FROM_CLI_QUERY_STRING = 'from_cli'
OIDC_CLAIMS_PARAMETER_SUPPORTED = 'claims_parameter_supported'