gcp_project_id: "vugle-dex"
gcp_location: "us"
gcp_processor_id: "94a35274ad2c4731"
gcp_credentials_path: "../dex_config/vugle-dex-1505d9c56161.json"

openai_api_key: "sk-DemsCfkJmaOG8_i5bXGMdhNqWpTP6813yASNbFLtZOT3BlbkFJ1_OYsnpaasD5q9iUYF4IhvBUOdyq2A2HtI5RzvrycA"
